# Generated by Django 5.2.5 on 2025-08-20 13:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MatchLeftOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B")],
                        max_length=1,
                        verbose_name="Метка (A или Б)",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Текст (например, формула или описание)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="match_left/",
                        verbose_name="Изображение (если есть)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент слева (А или Б)",
                "verbose_name_plural": "Элементы слева (А и Б)",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Номер задачи"
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст условия")),
                (
                    "illustration",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="illustrations/",
                        verbose_name="Поясняющее изображение",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("text", "Задача с кратким ответом"),
                            ("match", "Установить соответствие"),
                        ],
                        default="text",
                        max_length=10,
                        verbose_name="Тип задания",
                    ),
                ),
                (
                    "answer",
                    models.CharField(
                        blank=True,
                        help_text="Заполняется только для задач с типом 'text'",
                        max_length=50,
                        null=True,
                        verbose_name="Верный ответ (для краткого ответа)",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Заполняется только для задач с типом 'text'",
                        max_length=7,
                        null=True,
                        verbose_name="Единица измерения",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Время создания",
                    ),
                ),
            ],
            options={
                "verbose_name": "задача",
                "verbose_name_plural": "задачи",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchRightOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "index",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4")],
                        verbose_name="Номер варианта (1–4)",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст варианта")),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="right_options",
                        to="problems.problem",
                        verbose_name="Задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант справа (1–4)",
                "verbose_name_plural": "Варианты справа (1–4)",
                "ordering": ["index"],
                "unique_together": {("problem", "index")},
            },
        ),
        migrations.CreateModel(
            name="MatchPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "left_option",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pair",
                        to="problems.matchleftoption",
                        verbose_name="Элемент слева (A или Б)",
                    ),
                ),
                (
                    "right_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairs",
                        to="problems.matchrightoption",
                        verbose_name="Правильный вариант справа (1–4)",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairs",
                        to="problems.problem",
                        verbose_name="Задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Соответствие (A → 1)",
                "verbose_name_plural": "Соответствия (A → 1)",
            },
        ),
        migrations.AddField(
            model_name="matchleftoption",
            name="problem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="left_options",
                to="problems.problem",
                verbose_name="Задача",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="matchleftoption",
            unique_together={("problem", "label")},
        ),
    ]
