# Generated by Django 5.2.5 on 2025-08-12 08:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Номер задачи"
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст условия")),
                (
                    "illustration",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="illustrations/",
                        verbose_name="Поясняющее изображение",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("text", "Задача с кратким ответом"),
                            ("match", "Установить соответствие"),
                        ],
                        default="text",
                        max_length=10,
                        verbose_name="Тип задания",
                    ),
                ),
                (
                    "answer",
                    models.CharField(
                        blank=True,
                        help_text="Заполняется только для задач с типом 'text'",
                        max_length=50,
                        null=True,
                        verbose_name="Верный ответ (для краткого ответа)",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Заполняется только для задач с типом 'text'",
                        max_length=7,
                        null=True,
                        verbose_name="Единица измерения",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Время создания",
                    ),
                ),
            ],
            options={
                "verbose_name": "задача",
                "verbose_name_plural": "задачи",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchAnswerOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        max_length=1, verbose_name="Метка (например, 1, 2, 3, 4)"
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст варианта")),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_answer_options",
                        to="problems.problem",
                        verbose_name="Задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант ответа (справа)",
                "verbose_name_plural": "Варианты ответа (справа)",
                "ordering": ["label"],
                "unique_together": {("problem", "label")},
            },
        ),
        migrations.CreateModel(
            name="MatchOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=1, verbose_name="Метка")),
                (
                    "text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Текст формулы или описания"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="match_options/",
                        verbose_name="Изображение (если есть)",
                    ),
                ),
                (
                    "correct_answer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="problems.matchansweroption",
                        verbose_name="Правильный ответ",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_options",
                        to="problems.problem",
                        verbose_name="Задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Соответствие (A или Б)",
                "verbose_name_plural": "Соответствия (A и Б)",
                "ordering": ["label"],
                "unique_together": {("problem", "label")},
            },
        ),
    ]
